import type { Lane, Provenance } from "@/domain/types";

/**
 * THE OBJECTION REGISTER.
 *
 * Every marketing prototype ever built shows the funnel. Almost none of
 * them show the seven sentences that decide whether the funnel converts,
 * and those seven sentences are the job. A lead is generated by a
 * campaign and lost in a doorway, and the doorway is where the money
 * goes.
 *
 * A home services brand in this market does not lose a job because a
 * rival ran a better advert. It loses it because the ticket is higher
 * than the one van outfit's, because the household already has a
 * plumber, because the customer wants the repair and was quoted a
 * replacement, because somebody published a fifty seven dollar drain,
 * because a utility page is still advertising a tax credit that no
 * longer exists, because the person standing next to the broken water
 * heater does not own the building, and because a board wants three
 * bids. Those are not excuses a buyer invents. They are correct
 * observations, and a marketing manager who cannot answer them honestly
 * and fast is buying calls that the field then loses.
 *
 * So this file records the objection IN THE CUSTOMER'S OWN VOICE, the
 * answer that actually works, and, unusually, WHAT THE ANSWER COSTS.
 * The last one is the part most objection handling documents leave out
 * and the part a division director cares about, because every one of
 * these answers gives something away. Doing the repair the customer
 * asked for gives away the replacement ticket. Telling a homeowner
 * where the cheaper drain price is gives away the drain. Naming the
 * cost is the difference between a script and a plan.
 *
 * WHAT IS SOURCED AND WHAT IS NOT. The situations are sourced: the
 * published rival prices and their promo codes, the partnership one
 * rival declares with another, the terminated federal credit, the
 * reserved state programme, the utility factsheet still advertising
 * both. The objections themselves are marked illustrative except where
 * a reply in data/book.ts raised them, and the answers are judgements
 * written for this work sample. Nothing here is a quotation from a real
 * person, and no organisation is described as having said anything it
 * did not.
 */

export type ObjectionDisposition =
  /** Live. Somebody is raising this and it has not been answered. */
  | "open"
  /** Answered, and the job carried on. The answer worked. */
  | "answered"
  /** This is why the job died. Recorded, because a register that only
   *  logs wins teaches nothing. */
  | "lost-to-it";

export interface Objection {
  id: string;
  /** A short handle for a chip or a table cell. */
  short: string;
  /** The objection as a customer would actually say it. First person. */
  voice: string;
  /** Which lanes raise this one. Not all of them raise all of these. */
  lanes: Lane[];
  /** Why they are right to raise it. Concede this before answering. */
  why: string;
  /** The answer that works. Plain, specific, and honest. */
  answer: string;
  /** What answering this way costs the brand. Sometimes zero, and that
   *  is worth saying out loud rather than leaving to be assumed. */
  cost: string;
  /** The offer in data/venue.ts that this answer leans on, if any. */
  offerId?: string;
  /** How hard this one is, in this territory and this season. */
  severity: "structural" | "high" | "medium";
  source?: string;
  provenance: Provenance;
}

const ALL_LANES: Lane[] = [
  "hvac",
  "plumbing",
  "electrical",
  "multi-service",
  "drain-sewer",
  "partner-employer",
  "partner-property",
  "partner-community",
  "water-heater",
];

/*
  WHICH OF THESE SEVEN THE WATER HEATER LANE ACTUALLY RAISES, decided
  one row at a time rather than by ticking the box on all of them.

  It gets the two rows marked for every lane and one more. "Cheaper
  quote in hand" is the same sentence at a water heater as at a
  furnace, because a tank swap is the most shopped job in the trade and
  the price is on twenty other websites by lunchtime. "Just the repair"
  lands hard, because a leaking tank is exactly the job where a
  replacement quote looks like an upsell to somebody who wanted a
  thermostat replaced. "The rebate I read about" is added below, and
  this is the lane where it matters most: SoCalGas pays 300 to 575 on a
  high efficiency storage tank and 80 to 1,500 on a tankless replacing
  one, which is real live money against a ticket small enough for the
  rebate to decide the sale.

  The other four are left off on purpose. "The fifty seven dollar
  drain" is a drain aisle number and nobody quotes it at a water
  heater. "Three bids for the board" assumes a committee, and a tank
  that has already flooded a garage is not going to a committee. "The
  landlord decides" is genuinely raised at water heaters and is left
  off here only because the property lane already carries it, which is
  a judgement worth arguing with. "We already have a guy" belongs to
  the trades a household calls twice a year, and almost nobody has a
  water heater guy. A register that showed all seven on every lane
  would be a register nobody read twice.
*/

export const OBJECTIONS: Objection[] = [
  /*
    THE MOST IMPORTANT ROW IN THIS FILE.

    It is first because it is true of every conversation in every lane,
    because the whole market has trained customers to raise it, and
    because the honest answer to it is the argument this console exists
    to make.
  */
  {
    id: "no-published-price",
    short: "Cheaper quote in hand",
    voice:
      "I have a written quote from a smaller outfit that is hundreds under yours for the same equipment. Nothing on your site tells me what the difference buys. Talk me out of it.",
    lanes: ALL_LANES,
    why: "They are describing something real, and the market made it. Thirteen rival brands were profiled across these five counties and not one of them publishes what its membership costs. Every one names a plan and hides the number. So the only figure a homeowner can compare in ninety seconds is the coupon on the ticket, and on that one number a two van outfit with no dispatcher and no call centre wins every time. The customer is not being cheap. They are comparing the only thing anybody has given them to compare.",
    answer:
      "Do not defend the gap with adjectives. Warranty, uniforms and background checks are what every brand in this market says, and a homeowner has read all of it. Put a second number on the table instead: what the membership costs a month, what it covers, and what the visit they are buying today costs a member. That is the one comparison the smaller outfit cannot enter and the one number no rival publishes, so it is the only claim in this market that cannot be beaten by printing a smaller coupon. Then say plainly what cannot be done: a price cannot be matched against a scope nobody has written down, so put the scope in writing beside theirs and let them read the difference rather than being told about it.",
    cost: "Margin on the ticket, sometimes, and something larger. Publishing a monthly price gives away the one figure the entire market is holding back, it cannot be unpublished, and it invites every rival to undercut a number they can finally see. The argument for doing it anyway is that recurring revenue is worth more than a coupon click, and that argument has to be made to a division rather than assumed.",
    severity: "structural",
    source: "https://servicechampions.com/champ-rewards/",
    provenance: "public",
  },
  /*
    THE ONE THE FIELD GETS WRONG MOST OFTEN, and the reason it gets it
    wrong is that the customer is reading a page that is still live.
  */
  {
    id: "no-opening-date",
    short: "The rebate I read about",
    voice:
      "The utility's own factsheet says there is a thousand dollars for a heat pump and I read about a two thousand dollar federal credit. Is that still available, and why is none of it on your quote?",
    lanes: [
      "hvac",
      "plumbing",
      "partner-property",
      "electrical",
      "multi-service",
      "water-heater",
    ],
    why: "They are not confused and they are not haggling. They are quoting pages that are still published. The federal 25C credit is terminated for property placed in service after 31 December 2025, and the test is placed in service rather than paid, so even a deposit taken in December 2025 with the install finished in January 2026 earns nothing. TECH Clean California single family money has been fully reserved in Southern California since 7 January 2026 and statewide since 24 February 2026. Golden State Rebates has ended altogether. And Southern California Edison's own consolidated heat pump factsheet still advertises the TECH money, while its rebates page still links Golden State. The customer read it correctly. The page is wrong.",
    answer:
      "Never say that ended and stop, because a rep who contradicts a utility website without producing a better one loses the room. Three moves, in order. Concede the page: they read it correctly, it is still up, and it is out of date. Then name what IS live, with the figure attached. SoCalGas Home Energy Efficiency Rebates are funded through 31 December 2026, at 300 to 575 on a high efficiency storage water heater, 80 to 1,500 on a tankless replacing a tank, and 1.40 to 25 per kBTUh on an ENERGY STAR furnace, which is the most reliable pool in the region because it has a stated end date and no reservation queue. Inside the city of Los Angeles, LADWP pays up to 2,500 per ton on heat pump HVAC and up to 2,500 on a heat pump water heater, raised on 1 November 2025, and LADWP's own 2024 newsletter pages still print the old 300 per ton, so a rival quoting from those is under-quoting the customer by thousands. Riverside pays 750 per ton and 25 dollars towards a tune-up. Then write the live figure on the quote as a line the customer applies for, never as a discount already taken, because every one of these is first come first served and none is guaranteed. Multifamily money at up to 14,000 per unit stays out of the conversation entirely: the Energy Commission says that intake is open and TECH says it is paused, and a figure two public bodies disagree about is not a figure to put in front of a customer.",
    cost: "Real money at the kitchen table. An honest answer takes away the two thousand dollars the customer had already counted, in person, and some of those jobs do not survive it. It also costs a standing job for somebody: the live money list has to be re-read every month, because the only thing this market proves is that rebate pages go stale and stay up.",
    offerId: "first-fifty",
    severity: "structural",
    source: "https://www.sce.com/factsheet/ConsolidatedHeatPumpPrograms",
    provenance: "public",
  },
  {
    id: "cannot-tour",
    short: "Three bids for the board",
    voice:
      "I cannot sign this. The board wants three bids on a job this size and it meets once a month.",
    lanes: [
      "multi-service",
      "partner-employer",
      "drain-sewer",
      "hvac",
      "partner-community",
      "plumbing",
    ],
    why: "Correct, and any facilities manager who signed without the bids would be worse at their job. A committee that waives its own rule has to defend the waiver later. It is also the format the whole market has trained buyers into: when every brand publishes a coupon and none publishes a plan, the only way a board can compare anything is to collect three sheets of paper.",
    answer:
      "Be one of the three, in the format the board actually reads. Send a document that survives being passed around a table: scope, exclusions, the licence number, the warranty labour term, the response commitment and one named contact. Ask what the other two are being asked to quote, because a board comparing three different scopes is not comparing anything, and the bid that defines the scope usually sets it. Ask for the meeting date and get onto the agenda rather than into an inbox. Then offer the job that does not need three bids at all: the tune-up, the drain call, the inspection, which puts a technician inside their building before the vote and gives somebody in the room a reason to argue for you.",
    cost: "Weeks, and a bid you will lose roughly two times in three. The cycle belongs to the board and any attempt to compress it reads as pressure, so the cost is patience plus the writing time on every losing document.",
    offerId: "founding-partner-tour",
    severity: "high",
    provenance: "illustrative",
  },
  {
    id: "already-committed",
    short: "We already have a guy",
    voice:
      "We have used the same plumber for eleven years. He knows the building and he answers his phone.",
    lanes: ["drain-sewer", "multi-service", "partner-community", "partner-employer"],
    why: "This came back from a real account in this territory and it is the most useful no in the register. An incumbent is not an objection to be overcome, it is a relationship with knowledge in it, and the knowledge is genuinely worth money. Attacking him insults the customer's judgement and loses the next call as well as this one.",
    answer:
      "Do not try to replace him. Ask what he does not do. A one van plumber generally does not carry HVAC, does not carry electrical, does not run a camera, and does not answer at two in the morning in August, and the multi-service brands in this market exist because of exactly that gap. Take the work he is not there for, do it well, and be the second number in the phone rather than a replacement for the first. Then find out when he retires, because the trade is ageing and that date is worth more than this call.",
    cost: "A year of patience, one diary entry, and a smaller first job than the one you rang about. It costs nothing except the temptation to keep selling into a closed door.",
    severity: "medium",
    source: "Reply recorded in data/book.ts, 10 September 2026",
    provenance: "illustrative",
  },
  {
    id: "unproven-venue",
    short: "Just the repair",
    voice:
      "I did not ask for a new system. Fix the one I have and tell me what that costs.",
    lanes: ALL_LANES,
    why: "They are right to be suspicious. Every brand profiled in this market publishes a replacement incentive, from a flat 500 off to ceilings of 1,500 and 2,000, and several publish a discounted diagnostic whose commercial job is to put a technician in front of equipment old enough to condemn. A customer who suspects the cheap visit is a sales call has read the market accurately.",
    answer:
      "Do the repair they asked for, and quote it before touching it. Then leave them the three facts that make the replacement conversation honest later: the age of the equipment, the refrigerant it runs on, and what its parts cost now. R-410A is in glut today and its service cost climbs towards the 2029 step down, which is a repair versus replace argument with a date on it rather than a scare. Do not run scarcity copy about the A2L changeover: that story is stale, A2L was 99 per cent of new ducted sales by June 2026, and a customer who checks it will catch you. If the fix holds for two seasons, say so. If it will not, say what fails next and roughly when, and let them decide in their own time.",
    cost: "The replacement ticket today, on purpose. What it buys is the maintenance visit, the membership conversation and the replacement when the system genuinely fails, which is worth more than one condemned furnace and a household that tells the street about it.",
    offerId: "spirit-night-first-quarter",
    severity: "high",
    provenance: "illustrative",
  },
  {
    id: "budget-next-fiscal",
    short: "The landlord decides",
    voice:
      "I only rent. The landlord decides and I do not have his number to hand.",
    lanes: [
      "hvac",
      "plumbing",
      "partner-community",
      "multi-service",
      "partner-property",
      "partner-employer",
    ],
    why: "True, and it is the commonest dead end in the property lane. The person standing next to the failed water heater is not the person who pays for it, and a tenant who authorises a replacement can be billed for it themselves. Arguing with that is asking somebody to take a risk on your behalf.",
    answer:
      "Serve the tenant and capture the owner. Do the diagnostic, then put it in writing addressed to the property rather than to the person: the fault, two options, and the cost of doing nothing through a hot September. Give the tenant a copy they can forward in one message, because the forwarded document is what actually reaches the decision. Ask for the managing agent rather than the owner, since agents hold portfolios and owners hold one house. And note that under AB 1327 the contract now has to carry an email address and allow cancellation by email, which means an emailed authorisation from an absent owner is the normal way this gets signed rather than a favour.",
    cost: "A diagnostic that may never be paid for and a written report sent to somebody who did not ask for one. The bet is that the doors behind the agent are worth more than the single job, and on a portfolio it usually is.",
    offerId: "midweek-daytime-lock",
    severity: "medium",
    provenance: "illustrative",
  },
  /*
    THE ONE WITH THE GENUINELY INTERESTING ANSWER, kept last because it
    is the one a reader is most likely to remember.
  */
  {
    id: "we-use-dave-and-busters",
    short: "The fifty seven dollar drain",
    voice:
      "I have seen a fifty seven dollar drain clearing advertised in this area. Will you match it?",
    lanes: ["multi-service", "drain-sewer", "partner-community", "plumbing", "partner-employer"],
    why: "Yes, they have, and the instinct to attack the number is the wrong one. That price is published with a promo code on the home page of a brand working the same five counties. A second brand publishes seventy seven. Mike Diamond and all three ARS storefronts sit at ninety nine, which has hardened into the market's default. It is a real, checkable figure and pretending otherwise insults somebody who has done ninety seconds of homework.",
    answer:
      "Say the thing they do not expect. The fifty seven and the seventy seven come from two brands that publish a partnership with each other, so a rep matching the floor is bidding against a price two partners set together as a way into the house. Then be specific about what the number buys: it is a drain clearing with conditions on access and length printed beside it, and the free camera inspection everybody advertises is published by four brands in this market, which makes it table stakes rather than a favour. So do not match it. Quote the drain honestly, name what is included and what is not, and if what they want is the cheapest possible clear, tell them where it is. The household that was told the truth about a fifty seven dollar coupon is the household that rings about the water heater.",
    cost: "This drain, sometimes. A rep who volunteers where the cheaper number is loses that job and is believed on the next twelve things, and there is no version of matching a loss leader that ends with a profitable relationship.",
    severity: "medium",
    source: "https://www.nexgenairandplumbing.com/about-us/",
    provenance: "public",
  },
];

export const OBJECTION_BY_ID: Record<string, Objection> = Object.fromEntries(
  OBJECTIONS.map((o) => [o.id, o]),
);

/**
 * Which objections a given lane actually hits.
 *
 * A register that shows all seven on every lane board is a register
 * nobody reads twice. Nobody quotes a drain coupon at an electrical
 * panel, and a household with a failed condenser in August is not
 * waiting for a board to meet.
 */
export function objectionsForLane(lane: Lane): Objection[] {
  return OBJECTIONS.filter((o) => o.lanes.includes(lane));
}

export const SEVERITY_META: Record<
  Objection["severity"],
  { label: string; glyph: string; cssVar: string; note: string }
> = {
  structural: {
    label: "Structural",
    glyph: "▲",
    cssVar: "var(--risk)",
    note: "True of every conversation, in every lane, for as long as the market prices this way and the utility pages stay stale. These do not get solved, they get answered well.",
  },
  high: {
    label: "High",
    glyph: "◑",
    cssVar: "var(--warn)",
    note: "Blocks the largest tickets specifically. Answerable, and the answer costs the brand something real.",
  },
  medium: {
    label: "Medium",
    glyph: "○",
    cssVar: "var(--neutral)",
    note: "Comes up often, rarely fatal, and usually contains the next job inside the refusal.",
  },
};
